# Generated by Django 4.1.13 on 2024-12-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='door_no',
            new_name='doorNo',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='mobile_no',
            new_name='mobileNo',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='street_name',
            new_name='streetname',
        ),
    ]
